image: node:16.18.0 # change to match your node version

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-pages:
  stage: build
  script:
  - rm -rf build
  - CI=false npm install
  - CI=false npm run build
  - rm -rf ppublic
  - cp build/index.html build/404.html
  - mv build public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - ls
  artifacts:
    paths:
      - public